---
- hosts: proxmox_server
  vars:
    id_list:
      - "{{ k8s_master_id }}"
      - "{{ k8s_node1_id }}"
      - "{{ k8s_node2_id }}"
      - "{{ k8s_node3_id }}"

      
  tasks: 
      - name: Stopping the LXC instances.
        shell: pct stop {{ item }}
        with_items: "{{ id_list }}"
        ignore_errors: yes

      - name: Destroying the LXC instances.
        shell: pct destroy {{ item }}
        with_items: "{{ id_list }}"
        ignore_errors: yes

      - name: Deleting the Resource Pool.
        shell: pvesh delete /pools/{{ k8s_resource_pool }}

      - name: Removing the overlay kernel module from /etc/modules.
        replace: 
          path: /etc/modules
          regexp: '^overlay$'
        ignore_errors: yes

      - name: Stopping the overlay module on the Proxmox server.
        modprobe:
          name: overlay
          state: absent
        ignore_errors: yes

      - name: Deleting the LXC template.
        shell: pveam remove {{ template_storage }}:vztmpl/{{ lxc_template }}
        ignore_errors: yes

      - name: Deleting the ~/.kube directory.
        local_action:
          module: file
          path: ~/.kube
          state: absent
        ignore_errors: yes
