---
- hosts: proxmox_server
  tasks: 
      - name: Stopping the Kubernetes master container. (If applicable)
        shell: pct stop {{ k8s_master_id }}
        ignore_errors: yes

      - name: Stopping the first Kubernetes node container. (If applicable)
        shell: pct stop {{ k8s_node1_id }}
        ignore_errors: yes

      - name: Stopping the second Kubernetes node container. (If applicable)
        shell: pct stop {{ k8s_node2_id }}
        ignore_errors: yes

      - name: Stopping the third Kubernetes node container. (If applicable)
        shell: pct stop {{ k8s_node3_id }}
        ignore_errors: yes

      - name: Destroying the Kubernetes master container. (If applicable)
        shell: pct destroy {{ k8s_master_id }}
        ignore_errors: yes

      - name: Destroying the first Kubernetes node container. (If applicable)
        shell: pct destroy {{ k8s_node1_id }}
        ignore_errors: yes

      - name: Destroying the second Kubernetes node container. (If applicable)
        shell: pct destroy {{ k8s_node2_id }}
        ignore_errors: yes

      - name: Destroying the third Kubernetes node container. (If applicable)
        shell: pct destroy {{ k8s_node3_id }}
        ignore_errors: yes

      - name: Destroying the Kubernetes VM template. (If applicable)
        shell: qm destroy {{ proxmox_template_id }}
        ignore_errors: yes

      - name: Destroying the Kubernetes Resource Pool.
        shell: pvesh delete /pools/{{ k8s_resource_pool }}
        ignore_errors: yes

      - name: Removing the overlay kernel module from /etc/modules. (If applicable)
        replace: 
          path: /etc/modules
          regexp: '^overlay$'
        ignore_errors: yes

      - name: Stopping the overlay module on the Proxmox server. (If applicable)
        modprobe:
          name: overlay
          state: absent
        ignore_errors: yes

      - name: Deleting the LXC template.
        shell: pveam remove {{ template_storage }}:vztmpl/{{ lxc_template }}
        ignore_errors: yes

      - name: Deleting the ~/.kube directory.
        local_action:
          module: file
          path: ~/.kube
          state: absent
        ignore_errors: yes
