---
- hosts: proxmox_server
  vars:
    id_list:
      - "{{ k8s_master_id }}"
      - "{{ k8s_node1_id }}"
      - "{{ k8s_node2_id }}"
      - "{{ k8s_node3_id }}"
    id_size_list:
      - { id: "{{ k8s_master_id }}", size: "{{ k8s_master_size }}" }
      - { id: "{{ k8s_node1_id }}", size: "{{ k8s_node1_size }}" }
      - { id: "{{ k8s_node2_id }}", size: "{{ k8s_node2_size }}" }
      - { id: "{{ k8s_node3_id }}", size: "{{ k8s_node3_size }}" }  


  tasks:
      - name: Creating a resource pool for the compute resources.
        shell: pvesh create /pools -poolid "{{ k8s_resource_pool }}" --Comment "Kubernetes Cluster made from CentOS 7 Linux Containers"
        ignore_errors: yes 

      - name: Downloading the newest CentOS LXC template.
        shell: pveam download {{ template_storage }} {{ lxc_template }}

      - name: Provisioning the LXC instances.
        shell: >
            pct create {{ item.id }} {{ template_storage }}:vztmpl/{{ lxc_template }}
            --pool "{{ k8s_resource_pool }}" 
            --description "Kubernetes LXC Instance"
            --hostname "{{ item.hn }}" 
            --cores "{{ item.cpu }}"
            --memory "{{ item.mem }}" 
            --net0 "name=eth0,bridge={{ item.bridge }},ip={{ item.ip }}{{ item.sn }},gw={{ item.gw }},ip6=dhcp"
            --nameserver "{{ item.ns }}"
            --searchdomain "{{ item.sd }}"
            --ostype "centos" 
            --swap "0" 
            --storage "{{ item.stg }}" 
            --ssh-public-keys "{{ k8s_ssh_key }}"
        with_items:
          - { id: "{{ k8s_master_id }}", hn: "{{ k8s_master_hn }}", cpu: "{{ k8s_master_cpu }}", mem: "{{ k8s_master_mem }}", bridge: "{{ k8s_master_bridge }}", ip: "{{ k8s_master_ip }}", sn: "{{ k8s_master_sn }}", gw: "{{ k8s_master_gw }}", ns: "{{ k8s_master_ns }}", sd: "{{ k8s_master_sd }}", stg: "{{ k8s_master_stg }}" }
          - { id: "{{ k8s_node1_id }}", hn: "{{ k8s_node1_hn }}", cpu: "{{ k8s_node1_cpu }}", mem: "{{ k8s_node1_mem }}", bridge: "{{ k8s_node1_bridge }}", ip: "{{ k8s_node1_ip }}", sn: "{{ k8s_node1_sn }}", gw: "{{ k8s_node1_gw }}", ns: "{{ k8s_node1_ns }}", sd: "{{ k8s_node1_sd }}", stg: "{{ k8s_node1_stg }}" }
          - { id: "{{ k8s_node2_id }}", hn: "{{ k8s_node2_hn }}", cpu: "{{ k8s_node2_cpu }}", mem: "{{ k8s_node2_mem }}", bridge: "{{ k8s_node2_bridge }}", ip: "{{ k8s_node2_ip }}", sn: "{{ k8s_node2_sn }}", gw: "{{ k8s_node2_gw }}", ns: "{{ k8s_node2_ns }}", sd: "{{ k8s_node2_sd }}", stg: "{{ k8s_node2_stg }}" }
          - { id: "{{ k8s_node3_id }}", hn: "{{ k8s_node3_hn }}", cpu: "{{ k8s_node3_cpu }}", mem: "{{ k8s_node3_mem }}", bridge: "{{ k8s_node3_bridge }}", ip: "{{ k8s_node3_ip }}", sn: "{{ k8s_node3_sn }}", gw: "{{ k8s_node3_gw }}", ns: "{{ k8s_node3_ns }}", sd: "{{ k8s_node3_sd }}", stg: "{{ k8s_node3_stg }}" }

      - name: Pausing for 5 seconds to allow the containers to finish being created.
        wait_for: timeout=5

      - name: Resizing the volumes.
        shell: pct resize {{ item.id }} rootfs {{ item.size }} 
        with_items: "{{ id_size_list }}"

      - name: Starting the containers.
        shell: pct start {{ item }}
        with_items: "{{ id_list }}"

      - name: Installing openssh-server & sudo.
        shell: lxc-attach -n {{ item }} -- yum install -y openssh-server sudo
        with_items: "{{ id_list }}"

      - name: Enabling & Starting sshd.
        shell: lxc-attach -n {{ item }} -- systemctl enable --now sshd
        with_items: "{{ id_list }}"

      - name: Creating a centos user.
        shell: lxc-attach -n {{ item }} -- adduser -G wheel centos
        with_items: "{{ id_list }}"

      - name: Configuring centos to be a passwordless sudoer.
        shell: lxc-attach -n {{ item }} -- sed --in-place 's/^#\s*\(%wheel\s\+ALL=(ALL)\s\+NOPASSWD:\s\+ALL\)/\1/' /etc/sudoers
        with_items: "{{ id_list }}"

      - name: Creating an  ~/.ssh directory.
        shell: lxc-attach -n {{ item }} -- mkdir /home/centos/.ssh
        with_items: "{{ id_list }}"

      - name: Adding the ssh key.
        shell: lxc-attach -n {{ item }} -- cp /root/.ssh/authorized_keys /home/centos/.ssh/authorized_keys
        with_items: "{{ id_list }}"

      - name: Setting the correct permissions of the authorized_keys file.
        shell: lxc-attach -n {{ item }} -- chown -R centos /home/centos/.ssh/
        with_items: "{{ id_list }}"
