---
- hosts: proxmox_server
  vars:
    id_list:
      - "{{ k8s_master_id }}"
      - "{{ k8s_node1_id }}"
      - "{{ k8s_node2_id }}"
      - "{{ k8s_node3_id }}"


  tasks: 
    - name: Enabling the overlay kernel module.
      shell: echo overlay >> /etc/modules

    - name: Configuring the overlay kernel module to be loaded on boot.
      lineinfile:
        path: /etc/modules
        line: 'overlay'

    - name: Loading the overlay kernel module.
      modprobe: 
        name: overlay

    - name: Adding some additional privileges to the containers.
      shell: |
        echo "
        lxc.apparmor.profile: unconfined
        lxc.cap.drop: 
        lxc.cgroup.devices.allow: a
        lxc.mount.auto: proc:rw sys:rw" >> /etc/pve/lxc/{{ item }}.conf
      with_items: "{{ id_list }}"


- hosts: k8s_master:k8s_nodes
  tasks:
      - name: Enabling the systemd module for rc-local.
        become: yes
        systemd:
            state: started
            name: rc-local
            enabled: yes

      - name: Setting the executable bit for rc.local.
        become: yes
        file:
          path: /etc/rc.local
          mode: a+x

      - name: Enabling the shared mount.
        become: yes
        shell: |
          echo "#!/bin/sh -e
          mount --make-rshared /" > /etc/rc.local

      - name: Copying the docker.service for override.
        become: yes
        shell:  cp /{lib,etc}/systemd/system/docker.service

      - name: Rebooting the containers.
        become: yes
        reboot:
